# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AC-iOS-Final' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AC-iOS-Final
    pod 'Firebase/Storage'
    pod ‘Firebase/Database’
    pod ‘Firebase/Auth’
    pod ‘Firebase/Core’
    pod ‘SnapKit’, ‘~> 4.0.0’
    pod ‘Kingfisher’, ‘~> 4.0’
    pod 'CodableFirebase'
    pod ‘ILLoginKit’
    pod 'AZTabBar'
    pod 'EasyNotificationBadge'
    pod 'Material', '~> 2.0'
end
